### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DarthMikeSundays** [paradigm-sy/vscode-css-variables-autocomplete#1]
First thanks for making this usefull package! Second for some reason I have setup the configuration and it doesn't seem to work. Maybe I am doing something wrong or isn't this package yet ready for production?
Thanks in advance for any help,

**Comment by IanVS** [comment]
I've pushed up a PR that fixes this bug, but in the meantime, a workaround is to specify an explicit value for the `languageModes` like:

```json
"cssVarriablesAutocomplete.languageModes": ["css", "postcss"]
```
