### ISSUE TITLE
Add custom notation

### ISSUE THREAD

**Issue by equinusocio** [paradigm-sy/vscode-css-variables-autocomplete#6]
In css we can define custom environment variables like `env(--my-custom-var)`. So it would be useful if the extension could let us to choose if we want `var()` or `env` when an item is selected.

Another solution would be to prevent the extension from adding `var()` around the property, so if i write `--`:

```css
color: env(--
```

becomes

```css
color: env(--my-var
```

instead of:

```css
color: env(var(--my-var
```

by just replacing my value and without adding the `var()` notation

**Comment by IanVS** [comment]
I think it should be easy to prevent `env(var(` by updating the regex that I added in https://github.com/paradigm-sy/vscode-css-variables-autocomplete/pull/4/files#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R78.
